### ISSUE TITLE
just a digital old clock

### ISSUE THREAD

**Issue by davejakenic** [PaulleDemon/tkTimePicker#5]
Hi,

I try to figure out how to embed the old digital clock only.

```
from tktimepicker import AnalogPicker, AnalogThemes, DigitalThemes, SpinTimePickerModern, constants     # pip install tkTimePicker

time_picker =  SpinTimePickerModern(frame_host_row4, type=constants.HOURS24 ) # does not show on screen
time_picker.pack(expand=True, fill="both")
theme = DigitalThemes(time_picker)   # dont exist
theme.setSpinTimeold()
time_picker.pack(side='left')
```

Can you make a minimum working example with picture?

**Comment by PaulleDemon** [comment]
@davejakenic Hello, there SpinTimepicker doesn't take type parameter. instead use `SpinTimePickerModern.addAll(constants.HOURS24)`. The digital theme doesn't exist please configure your own themes using the configure method. Please refer this example https://github.com/PaulleDemon/tkTimePicker/blob/master/examples/SpinTimePickerExample.py

The correct code would be as shown below
```
from tkinter import *
from tktimepicker import AnalogPicker, AnalogThemes, SpinTimePickerModern, 

root = Tk()

time_picker =  SpinTimePickerModern(root) # does not show on screen
time_picker.pack(expand=True, fill="both")
time_picker.addAll(constants.HOURS24)  

root.mainloop()
```

Let me know if you have any other questions. otherwise I'll close this issue. Thank you.

**Comment by davejakenic** [comment]
Your solution works; even with the old scheme. Thank you very much.

Before your answer, I have though adapted the analogue scheme:

![image](https://user-images.githubusercontent.com/77342203/179347196-a912e90c-6bb4-417c-b70a-6d7adfa226ab.png)

I have two issues that you might be able to help with:

1) the analogue clock occupies unused space in x-direction. (there is all the blank space, yet I cannot manage to make it narrower.) is there a way to make it thinner in x? It should be able to fit in the same width as the calendar.

2) when I scroll with mouse scroll wheel in the digital representation, then the analogue position does not update. As I am unfamiliar to python and your code, particularly the polymorphism, I was wondering if there is a few-lines-solution to keeping the ditigal and analogue representation always aligned.

3) Probably a very stupid question: How do I get the time out of it? I tried: ```activation_time  = time_picker.current()```, which I saw in what I thought was the base class. It raises the error that such routine does not exist.

**Comment by PaulleDemon** [comment]
@davejakenic Hello there; I'll answer the question one by one.

1. No, because for the clock to remain a circle, it has to maintain 1:1 ratio (i, e). The height and width must remain the same; otherwise, it becomes an ellipse. Look at the time picker in an android phone; it will always have some unused space. The only way to reduce that is to make the frame holding the timepicker square.

2. It's designed that way. It started to distract the user when using the mouse wheel on the digitalTimepicker to update the time, hence kept that way.

3. user `timepicker.time()` to get the time. refer to this example: https://github.com/PaulleDemon/tkTimePicker/blob/master/examples/AnalogTimePickerExample.py

If you have further questions, let me know, or else close the issue. Thank you.

**Comment by davejakenic** [comment]
Thank you very much for your detailed, timely, and kind responses!
